# Generated by Django 5.0.4 on 2024-04-30 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('slug', models.SlugField(blank=True, default='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='images/clothes')),
                ('model_image_1', models.ImageField(null=True, upload_to='images/clothes')),
                ('model_image_2', models.ImageField(null=True, upload_to='images/clothes')),
                ('other_image', models.ImageField(null=True, upload_to='images/clothes')),
            ],
        ),
        migrations.CreateModel(
            name='SizeClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XtraSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
                ('cant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=400)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clothes.clothes')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes', to='clothes.imageclothes'),
        ),
    ]
