# Generated by Django 5.0.4 on 2024-04-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes', to='clothes.sizeclothes'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='main_image',
            field=models.ImageField(upload_to='clothes'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='model_image_1',
            field=models.ImageField(null=True, upload_to='clothes'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='model_image_2',
            field=models.ImageField(null=True, upload_to='clothes'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='other_image',
            field=models.ImageField(null=True, upload_to='clothes'),
        ),
    ]
