# Generated by Django 5.0.4 on 2024-05-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_remove_characteristicsclothes_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='clothes',
            name='characteristics',
            field=models.ManyToManyField(to='clothes.characteristicsclothes'),
        ),
    ]
