# Generated by Django 5.0.4 on 2024-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_remove_clothes_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='imageclothes',
            name='characteristics',
            field=models.ManyToManyField(to='clothes.characteristicsclothes'),
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='images',
        ),
        migrations.AddField(
            model_name='clothes',
            name='images',
            field=models.ManyToManyField(to='clothes.imageclothes'),
        ),
    ]
