# Generated by Django 5.0.4 on 2024-05-01 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_remove_clothes_characteristics_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacteristicsClothes',
            new_name='SizeClothes',
        ),
        migrations.RemoveField(
            model_name='imageclothes',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='imageclothes',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='clothes.sizeclothes'),
        ),
    ]
