# Generated by Django 5.0.4 on 2024-05-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_rename_characteristicsclothes_sizeclothes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclothes',
            name='sizes',
        ),
        migrations.AddField(
            model_name='imageclothes',
            name='sizes',
            field=models.ManyToManyField(to='clothes.sizeclothes'),
        ),
    ]
