# Generated by Django 5.0.4 on 2024-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_clothes_avg_rating_clothes_slug_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.CharField(choices=[('hombres', 'Male'), ('mujeres', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('crop top', 'crop top'), ('top deportivos', 'top deportivos'), ('sets', 'sets'), ('leggings', 'leggings'), ('enterizos', 'enterizos'), ('shorts', 'shorts'), ('pantalonetas', 'pantalonetas'), ('camisetas', 'camisetas'), ('hoodies', 'hoodies'), ('buzo', 'buzo')], max_length=30),
        ),
    ]
