# Generated by Django 5.0.4 on 2024-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_size_alter_imageclothes_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='name',
            field=models.CharField(default='clothes', max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.IntegerField(choices=[(0, 'crop top'), (1, 'top deportivos'), (2, 'sets'), (3, 'leggings'), (4, 'enterizos'), (5, 'shorts'), (6, 'pantalonetas'), (7, 'camisetas'), (8, 'hoodies'), (9, 'buzo')], default=0),
        ),
    ]
