# Generated by Django 5.0.4 on 2024-05-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_clothes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicsClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XtraSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2)),
                ('cant', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.AddField(
            model_name='clothes',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes', to='clothes.characteristicsclothes'),
        ),
        migrations.DeleteModel(
            name='SizeClothes',
        ),
    ]
