# Generated by Django 5.0.4 on 2024-05-06 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_remove_comment_rating_clothes_rating_comment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
