# Generated by Django 5.0.4 on 2024-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_remove_clothes_rating_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=0),
        ),
    ]
