# Generated by Django 5.0.4 on 2024-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_alter_comment_comment_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='slug_type',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=0),
        ),
    ]
