# Generated by Django 5.0.4 on 2024-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_alter_clothes_gender_alter_clothes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
