# Generated by Django 5.0.4 on 2024-05-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_alter_clothes_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='avg_rating',
        ),
    ]
