# Generated by Django 5.0.4 on 2024-06-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_remove_clothes_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclothes',
            name='url_instagram',
            field=models.URLField(null=True, unique=True),
        ),
    ]
