# Generated by Django 5.0.4 on 2024-06-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_imageclothes_url_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclothes',
            name='in_instagram',
            field=models.BooleanField(default=False),
        ),
    ]
