# Generated by Django 5.0.4 on 2024-07-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_imageclothes_in_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclothes',
            name='main_image',
            field=models.ImageField(upload_to='clothes/'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='model_image_1',
            field=models.ImageField(null=True, upload_to='clothes/'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='model_image_2',
            field=models.ImageField(null=True, upload_to='clothes/'),
        ),
        migrations.AlterField(
            model_name='imageclothes',
            name='other_image',
            field=models.ImageField(null=True, upload_to='clothes/'),
        ),
    ]
