# Generated by Django 5.0.4 on 2024-05-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('payer_fullname', models.CharField(max_length=100)),
                ('payer_phone', models.CharField(max_length=10)),
                ('payer_address', models.CharField(max_length=100)),
                ('payer_email', models.EmailField(max_length=254)),
                ('shipments', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('date_order_created', models.DateField(auto_now=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchand_order', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('shipping_cost', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('net_received_amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('order_status', models.CharField(max_length=100)),
                ('payment_method_id', models.CharField(max_length=100)),
                ('payment_type_id', models.CharField(max_length=100)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_lastname', models.CharField(max_length=100)),
                ('payer_phone', models.CharField(max_length=10)),
                ('payer_address', models.CharField(max_length=100)),
                ('payer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('direct_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_payment', to='cart.directpayment')),
                ('mercadopago_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mercadopago_payment', to='cart.mercadopagopayment')),
            ],
        ),
    ]
