# Generated by Django 5.0.4 on 2024-05-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadopagopayment',
            name='payer_email',
        ),
        migrations.AddField(
            model_name='itemspayed',
            name='item_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='mercadopagopayment',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemspayed',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemspayed',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
