# Generated by Django 5.0.4 on 2024-05-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_mercadopagopayment_payer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directpayment',
            name='is_canceled',
        ),
        migrations.AddField(
            model_name='directpayment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
