# Generated by Django 5.0.4 on 2024-05-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_directpayment_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpayment',
            name='date_order_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
