# Generated by Django 5.0.4 on 2024-06-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_directpayment_directpayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercadopagopayment',
            old_name='merchand_order',
            new_name='merchant_order',
        ),
        migrations.AlterField(
            model_name='mercadopagopayment',
            name='iva',
            field=models.FloatField(default=0),
        ),
    ]
