# Generated by Django 5.0.4 on 2024-07-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_merchand_order_mercadopagopayment_merchant_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpayments',
            name='status',
            field=models.CharField(choices=[('aproved', 'aproved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending'),
        ),
    ]
